{% set name = "Commonmark" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 452f9dc859be7f06631ddcb328b6919c67984aca654e5fefb3914d54691aed60

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cmark = commonmark.cmark:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - commonmark/tests
  imports:
    - commonmark
    - commonmark.render
    - commonmark.tests
  requires:
    - pip
    - flake8
    - hypothesis
    - pytest
  commands:
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pip check
    - cmark --help
    - pytest -vv commonmark/tests/*

about:
  home: https://commonmark.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Python parser for the CommonMark Markdown spec
  description: |
    CommonMark-py is a pure Python port of jgm's commonmark.js, a Markdown
    parser and renderer for the CommonMark specification, using only native
    modules.
  dev_url: https://github.com/rtfd/commonmark.py
  doc_url: https://commonmark-py.readthedocs.io

extra:
  recipe-maintainers:
    - ericmjl
    - dpryan79
