# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KgkcurtyVma3762Oi3MeL5i8nxqbv8esG+rfMGW0Ooco1wMeVmjFy96nSQs5FGJ/JYIOmwuK7ARmkgMdVILeMlVLujApCsroK9tZbxlnLp61E0NDk8W6KYHs0Ow4t7moCTS5iS+dLHYFPMzL9ray47owoCe6+ewpoXhSICuAawp0lqsw62nbnGMcDgRcG4HDXnS3MMOK+/WTCL+6uw9k2BXRqh68OTqDNQxsEvtWRgYj33DvoS6dQjKt4Hl6wXQANEr6r8v6s5vxkc/dycY4F5i+nydOR6v9QDLiXiunsQPUTQv7BEQdbaBYuPDA69tZn/yHxg990A6pvPmWnZBPUSwwZPV7+YLOh1AqINT3dSHPCieZU9TS3X3hZuESy1HG+qyYYwAzt1Tr+GdnLRnCYxwDQFnIrcFHgt4+UrFKazBfBGTO/x7Nw1a4z5rUPvpHINo8N6M0U2SkeT8/zeLS7gE9BbFNW6bqlcL50QJhx3Som9QmHExIrWBIfAaptnUYSlrjkdmw6UKXzER4hGYshDJsDLDBeLjUsqL+GYY4dwWkxe1tpxWkVv7s/G4xsbdrgI2VRNwXXN3WIlp1Avu606+oHGo18bS8aBZF5L+3brORcOk1+GNKLdvlmjyuaEAf4fTqzJsdOGXFEKZiL/BRHdL5Ifl5smkX+YGMQMY5VGw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
