travis:
  secure:
    BINSTAR_TOKEN: KgkcurtyVma3762Oi3MeL5i8nxqbv8esG+rfMGW0Ooco1wMeVmjFy96nSQs5FGJ/JYIOmwuK7ARmkgMdVILeMlVLujApCsroK9tZbxlnLp61E0NDk8W6KYHs0Ow4t7moCTS5iS+dLHYFPMzL9ray47owoCe6+ewpoXhSICuAawp0lqsw62nbnGMcDgRcG4HDXnS3MMOK+/WTCL+6uw9k2BXRqh68OTqDNQxsEvtWRgYj33DvoS6dQjKt4Hl6wXQANEr6r8v6s5vxkc/dycY4F5i+nydOR6v9QDLiXiunsQPUTQv7BEQdbaBYuPDA69tZn/yHxg990A6pvPmWnZBPUSwwZPV7+YLOh1AqINT3dSHPCieZU9TS3X3hZuESy1HG+qyYYwAzt1Tr+GdnLRnCYxwDQFnIrcFHgt4+UrFKazBfBGTO/x7Nw1a4z5rUPvpHINo8N6M0U2SkeT8/zeLS7gE9BbFNW6bqlcL50QJhx3Som9QmHExIrWBIfAaptnUYSlrjkdmw6UKXzER4hGYshDJsDLDBeLjUsqL+GYY4dwWkxe1tpxWkVv7s/G4xsbdrgI2VRNwXXN3WIlp1Avu606+oHGo18bS8aBZF5L+3brORcOk1+GNKLdvlmjyuaEAf4fTqzJsdOGXFEKZiL/BRHdL5Ifl5smkX+YGMQMY5VGw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
