travis:
  secure:
    BINSTAR_TOKEN: eFuGCiNZtcstPJmPMhyA3Ka6OA0f8hDnz+PMWbJNMxZD/q0tg1Uh1VJmf6cHfRTGMwE2GKXIlTXVU0Dvlf2rr7lxr+NnJMBh4t2CaQRj5Iywh2Bx1DaRSfFbKQGCfC+1Ah0mzRVp7DDo6+5isD3xr7j88qFaADx4IIaSbbPLclFkafx581AEDOnbUdq21fJuv1BUfvtbKC8Ujdlyn6qRh9GiajidEzc6Yyup9rlBXY4pg36szDpGp1ARCWogUIhNWWMEI5SYVaf//D3h/F91maU23IpjxTJ1WsfW9dxIOlog12obvOnZRQ3yE3Tm1fSWWtPUtqgJIAcRiiqLDh9Js6s78KBixrpWrRowh91C0rg0FGpZDM7+bYywOmAUim7N7FHbtdR7v6A/dnr4l8z9nBUTf15r62maKryySIySlm+YcVD6RaErCe6M+gmX3IEDEZHQeyJuhb+euXne0xPgxDAb/aiu8NmiN+TyW4hF/fWWFLBNJ0b5wChxRp1/DPsuFIv2qdisD18MjXmkZx69pQ8vBfgBA7KtU/GYT8SNJMQJE9HeyvMFLS/Pypw9if+3kCSB1MXMhkJ7wejqj6jc97h4nXFVDdC6JERVriYAZbX8tAS2NguvFTZ/2xEw5uGGsHiPwtTPx4ndh6J4dPjd6TA+xdgQ5fWpJrt1UY3mvwg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
